apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: web-test
  name: web-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - image: rawmind/web-test
        imagePullPolicy: Always
        name: web-test
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
